name: Schedule Fetch Data

on:
  schedule:
    - cron: '*/10 * * * *' # Every 10 minutes
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger fetchData function
        run: |
          curl -X POST https://yoruakio.tech/api/fetchGithubData -H "Authorization: Bearer ${{ secrets.API_TOKEN }}"
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
